<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMcljWCZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMcljWCZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMcljWCZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMcljWCZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMcljWCZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'McljWCZ',
    'container.build_id' => '9a3fbbec',
    'container.build_time' => 1658735413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMcljWCZ');
